data-reader:
  train_csv: "data/raw/train.csv"
  test_csv: "data/raw/test.csv"
  target_col: "Culture"
feature-extractor:
  pipeline_path: "models/feature_extractor.pickle"
  features_path: "data/processed/features.csv"
model:
  path:
    fitted: "models/model.pickle"
    base: "models/model_base.pickle"
  params:
    max_depth: 4
    n_estimators: 250
  eval:
    k: 5
constants:
  seed: 42